version: '3.8'

services:
  web:
    build: ./src/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/chronographer
      - API_KEY=${API_KEY}
    depends_on:
      - db

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chronographer
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local
